(require 'org-tempo)
(setq org-src-preserve-indentation nil)
(setq org-edit-src-content-indentation 0)
(setq-default cursor-type 'bar)
(scroll-bar-mode -1)
(add-hook 'python-mode-hook
          (lambda()
            (pyenv-mode-set "emacsenv")))
(setq confirm-kill-processes nil)
;; (setq mac-command-key-is-meta nil)
(setq mac-command-modifier 'super)
(setq mac-option-modifier 'meta)
